
subcategories = [
    "A Sweet Affair",
    "All Things Rice",
    "All Types Of Flours",
    "All Your Breakfast Needs",
    "Atta",
    "Atta & Other Flours",
    "Be a Chef",
    "Binge Snacks",
    "Bread & Eggs",
    "Bread and Eggs",
    "Breads",
    "Breakfast & Sauces",
    "Breakfast And Sauces",
    "Breakfast Essential",
    "Breakfast Essentials",
    "Breakfast Fixes",
    "Carbonated Drinks",
    "Cereals",
    "Cereals & Sauces",
    "Chocolates & Candies - Deactivated",
    "Cofee",
    "Coffee",
    "Coffee & More",
    "Coffee An More",
    "Coffee And Mo",
    "Coffee And More",
    "Cold Drinks & Juices",
    "Cook Up",
    "Cook Your Best",
    "Cook Your Festive Favorites",
    "Cooking Basics",
    "Cooking Essentials",
    "Cooking Essentials G",
    "Cooking Must-Haves",
    "Cooking Staples at Best Price",
    "Cooking Staples at Best Prices",
    "Creamfill Bombs",
    "Curated Combo Packs",
    "Curated For You",
    "Dahi & Ice creams",
    "Daily Essentials",
    "Daily Household Needs",
    "Daily Pulses",
    "Dairy",
    "Dal",
    "Dal & Pulses",
    "Dawat-e-Ramadan Campaign",
    "Dinner",
    "Drinks & Mixers",
    "Drinks For Heroes",
    "Dry Fruit",
    "Dry Fruits",
    "Dry Fruits & Masala",
    "Dry Fruits & More",
    "Dry Fruits And Mo",
    "Dry Fruits And More",
    "Easy Cook Weekends",
    "Easy-Cook Weekends",
    "Eat Feast Repeat",
    "Everyday Cooking Essentials",
    "Everything Gourmet",
    "Exotic Veggies",
    "Explore Beauty",
    "Fish & Eggs",
    "Flours",
    "Food & Beverages",
    "For Flavourful Breaks",
    "For The Snacking Hour",
    "For Your Cooking Needs",
    "Fresh & Vegetables",
    "Fresheners",
    "Frozen",
    "Frozen Food & Ice Creams",
    "Fruit It Up",
    "Fruits",
    "Fruits & Vegetable",
    "Fruits & Vegetables",
    "Ghee",
    "Ghee & Oil",
    "Gourmet Selection",
    "Hand Picked Freshness",
    "Health Drinks",
    "Healthy & Organic",
    "Healthy Living",
    "Homemade Pizza",
    "Hot Beverages",
    "Ice Cream & Beverages",
    "Ice Creams & Beverages",
    "Ice Creams & Desserts",
    "Indian Namkeens",
    "Instant Food",
    "Instant Snacks",
    "Jaggery",
    "Juices & Mixers",
    "Juices & More",
    "Juices & Ready to Drink",
    "Kitchen Corner",
    "Kitchen Needs",
    "Late Night Cravings",
    "Late Night Cravings Sorted",
    "Lunch",
    "Masala",
    "Masala & Dry Fruits",
    "Masala and Dry Fruits",
    "Masalas & Dry Fruits",
    "Meat",
    "Meats",
    "Meats and Seafood",
    "Meaty Range",
    "Mega Munchies Mania",
    "Mixers",
    "Munch",
    "Munchie",
    "Munchies",
    "Munchies - Deactivated",
    "Namkeen",
    "Namkeen & Biscuits",
    "Namkeens & Biscuits",
    "Nuts & Seeds",
    "Nutty-licious Nutrition",
    "Oil",
    "Oil & Dal",
    "Oil & Dals",
    "Oil & Ghee",
    "Oil & More",
    "Oil An Dals",
    "Organic",
    "Organic Store",
    "Packaged Food",
    "Powdered Spices",
    "Pulses",
    "Quick bites",
    "Ready-To-Eat & More",
    "Refresh In An Instant",
    "Refreshing Beverages",
    "Refreshing Summers",
    "Regional Rice",
    "Rice",
    "Rice & Grains",
    "Rice & More",
    "Rice & Pulses",
    "Rice & Shine",
    "Rice Deals",
    "Rice_1",
    "Salt",
    "Sauces",
    "Snack Attack",
    "Soda",
    "Spices & Masala",
    "Spreads & Cheese",
    "Spreads & More",
    "Spreads & Sauces",
    "Staples",
    "Sugar",
    "Sugar & Jaggery",
    "Sweet Cravings",
    "Sweet Indulgence",
    "Sweet Something",
    "Sweet Tooth",
    "Sweet Treats",
    "Tastes Like Magic",
    "Tea",
    "Tea & Coffee",
    "Tea Coffee & More",
    "Ugadi",
    "Unlisted Collections",
    "Value Store",
    "Winter Food Fiesta",
    "Yummy Breakfast"
]
units = ['MILLIGRAM', 'GRAM', 'KILOGRAM', 'MILLILITRE', 'LITER', 'PIECE', 'COMBO']

